CREATE TABLE attendees (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP default CURRENT_TIMESTAMP
    CONSTRAINT attendees_events_id_fkey FOREIGN KEY (event_id) ON DELETE RESTRICT ON UPDATE CASCADE
);